const dataSiswa = [
    { npm: "23001", nama: "Andi Pratama", jk: "L" },
    { npm: "23002", nama: "Siti Aisyah", jk: "P" },
    { npm: "23003", nama: "Rizki Saputra", jk: "L" },
    { npm: "23004", nama: "Dedi Kurniawan", jk: "L" },
    { npm: "23005", nama: "Nurul Hidayah", jk: "P" },
    { npm: "23006", nama: "Agus Setiawan", jk: "L" },
    { npm: "23007", nama: "Putri Amelia", jk: "P" },
    { npm: "23008", nama: "Fajar Ramadhan", jk: "L" },
    { npm: "23009", nama: "Budi Santoso", jk: "L" },
    { npm: "23010", nama: "Dewi Lestari", jk: "P" },
    { npm: "23011", nama: "Rian Maulana", jk: "L" },
    { npm: "23012", nama: "Aulia Rahma", jk: "P" },
    { npm: "23013", nama: "Iqbal Fahri", jk: "L" },
    { npm: "23014", nama: "Hendra Wijaya", jk: "L" },
    { npm: "23015", nama: "Fitri Handayani", jk: "P" },
    { npm: "23016", nama: "Ardiansyah", jk: "L" },
    { npm: "23017", nama: "Nabila Zahra", jk: "P" },
    { npm: "23018", nama: "Robby Firmansyah", jk: "L" },
    { npm: "23019", nama: "Ilham Sapri", jk: "L" },
    { npm: "23020", nama: "Salsa Putri", jk: "P" },
    { npm: "23021", nama: "Yoga Pradana", jk: "L" },
    { npm: "23022", nama: "Maya Sari", jk: "P" },
    { npm: "23023", nama: "Eko Nugroho", jk: "L" },
    { npm: "23024", nama: "Bayu Prakoso", jk: "L" },
    { npm: "23025", nama: "Indah Permata", jk: "P" },
    { npm: "23026", nama: "Dimas Anggara", jk: "L" },
    { npm: "23027", nama: "Citra Lestari", jk: "P" },
    { npm: "23028", nama: "Ari Wibowo", jk: "L" },
    { npm: "23029", nama: "Rina Oktaviani", jk: "P" }
  ];

  